version: '2.2'
services:
    app:
      build:
        context: .
        dockerfile: ./deploy/Dockerfile
      ports:
        - "5005:5000"
      volumes:
        - ./app:/code
      environment:
        PYTHONUNBUFFERED: 1
        SENTRY_DSN: https://1234567890.ingest.sentry.io/111111111

    nginx:
      image: nginx:1.19.2
      volumes:
        - ./deploy/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./deploy/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      depends_on:
        - app
      ports:
        - 8080:80